### ISSUE TITLE
What about adding a additional field icon to store the achievement's icon url ?

### ISSUE THREAD

**Issue by strikerlulu** [assada/laravel-achievements#1]

**Comment by assada** [comment]
In my opinion, achievements are not always displayed as an icon(picture) by UI condition or your project is a API

**Comment by Strikerlulu** [comment]
In most of the case it has an icon...
So you are not interested in adding it ? or shall i fork?

**Comment by assada** [comment]
In today's world, more often do API. So, icons urls in model are not best solution.
