### ISSUE TITLE
Vendor:publish command not publishing the migration

### ISSUE THREAD

**Issue by iDiegoNL** [assada/laravel-achievements#14]
When running the `php artisan vendor:publish --provider="Assada\Achievements\AchievementsServiceProvider"` command, it responds with `Publishing complete`. However, only the `achievements.php` config file is published. And not the migration.

When trying to force run the command (`php artisan vendor:publish --provider="Assada\Achievements\AchievementsServiceProvider" --force`, I am greeted with the following exception:
```
  ErrorException 

  copy(): The second argument to copy() function cannot be a directory

  at F:\Phoenix-Dev\base\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:302
    298▕      * @return bool
    299▕      */
    300▕     public function copy($path, $target)
    301▕     {
  ➜ 302▕         return copy($path, $target);
    303▕     }
    304▕
    305▕     /**
    306▕      * Create a symlink to the target file or directory. On Windows, a hard link is created if the target is a file.

  1   F:\Phoenix-Dev\base\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:302
      copy("F:\Phoenix-Dev\base\vendor\assada\laravel-achievements\src/Migrations/0000_00_00_000000_create_achievements_tables.php", "F:\Phoenix-Dev\base\database\migrations")

  2   F:\Phoenix-Dev\base\vendor\laravel\framework\src\Illuminate\Foundation\Console\VendorPublishCommand.php:221
      Illuminate\Filesystem\Filesystem::copy("F:\Phoenix-Dev\base\vendor\assada\laravel-achievements\src/Migrations/0000_00_00_000000_create_achievements_tables.php", "F:\Phoenix-Dev\base\database\migrations")
```

What could be the cause of this problem?

**Comment by WayneFellows** [comment]
Did this bug ever get fixed my UserID is UUID and wont work is there any way to overide this ??

**Comment by haleyngonadi** [comment]
Any update on this? 👀

**Comment by vinodsptharsha** [comment]
Even after publishing the migration file the package's migration is still running. Thus giving me error of base table already exists. 
 0000_00_00_000000_create_achievements_tables .............................. 43ms DONE
2023_Feb_20_195204_create_achievements_tables .............................. 1ms FAIL


There is only one migration file in the migration folder.

Also, package migration class naming conventions need to be updated.
