### ISSUE TITLE
Foreign key in achievement_progress table has incorrect column type

### ISSUE THREAD

**Issue by mstralka** [assada/laravel-achievements#18]
In a MySQL database, the `id` field type in the `achievement_details` table is `UNSIGNED BIG INT` because the `$table->id();` command generates an unsigned big int field.
~~~php
// This generates an UNSIGNED BIG INT column.
$table->id();
~~~

In the `achievement_progress table`, the `achievement_id` field is created as:
~~~php
$table->unsignedInteger('achievement_id');
~~~

That causes a mismatch and MySQL won't create the foreign key.

It should be:
~~~php
$table->unsignedBigInteger('achievement_id');
~~~

**Comment by assada** [comment]
Thx, @mstralka for reporting, and @ahmdalgendi for PR!
