### ISSUE TITLE
Even after publishing the migration file the package's migration is still running

### ISSUE THREAD

**Issue by vinodsptharsha** [assada/laravel-achievements#24]
Even after publishing the migration file the package's migration is still running. Thus giving me error of base table already exists.
0000_00_00_000000_create_achievements_tables .............................. 43ms DONE
2023_Feb_20_195204_create_achievements_tables .............................. 1ms FAIL

There is only one migration file in the migration folder.

Also, package migration class naming conventions need to be updated.

**Comment by vinodsptharsha** [comment]
Is this package no longer maintained?

**Comment by reasecret** [comment]
@vinodsptharsha you don't need to publish migration files. Install the package and run migrate command.
