### ISSUE TITLE
Migrations | Config Table Names - Incomplete Implementation 

### ISSUE THREAD

**Issue by bayareawebpro** [assada/laravel-achievements#4]
Looks like you forgot to update the dropTable names to use the config: 

https://github.com/assada/laravel-achievements/blob/master/src/Migrations/0000_00_00_000000_create_achievements_tables.php#L67

```php
Schema::dropIfExists($this->achievement_progress);
Schema::dropIfExists($this->achievement_details);
```

Also Here:

https://github.com/assada/laravel-achievements/blob/master/src/Migrations/0000_00_00_000000_create_achievements_tables.php#L55

```php
$table->foreign('achievement_id')->references('id')->on($this->achievement_details);
```

**Comment by assada** [comment]
Thnx! Fixed https://github.com/assada/laravel-achievements/commit/6c0d8412e1a22ec3cc3bb73c7e9c9ebbeb7798dd
