### ISSUE TITLE
Activity of this Repo

### ISSUE THREAD

**Issue by MazzMazz** [assada/laravel-achievements#6]
We want to use your HardFork in our project and wanted to check in how active this repo is due the infrequent pushes and open Issues since March. If we contribute Code - are the Pull Requests handled or would they remain undhandled?

cc direct @assada

**Comment by assada** [comment]
Hi, @MazzMazz 
If your code is really useful for the project, then I will try to add it to the release as soon as I can! I will also try to help you with any problems you encounter.
